### ISSUE TITLE
Documentation: BSwap.Swap not working from USDT to ETH (binance-connector-dotnet)

### ISSUE THREAD

**Issue by minutd97** [binance/binance-connector-dotnet#34]
### Description

Hello, i am not sure what i am doing wrong, i am trying to make a swap from USDT to ETH but it gives me an "Exception of type 'Binance.Common.BinanceClientException' error. USDT to BUSD works fine. Any help will be appreciated, thank you.

CODE:

var bSwap = new BSwap(binanceUrl, binanceApiKey, binanceApiSecret);
var result = await bSwap.Swap("USDT", "ETH", 5.0m);
print(result);

**Comment by aisling-2** [comment]
Hello @minutd97,
Sorry for the late reply, although as mentioned in the README.md, regarding `Binance.Common.BinanceClientException`:

>     - This is thrown when server returns `4XX`, it's an issue from client side.
>     - Properties:
>         - `Code` - Server's error code, e.g. `-1102`
>         - `Message` - Server's error message, e.g. `Unknown order sent.`

So by looking at the BinanceClientException's error Message, you'll be able to know how to solve the problem.
Since it's been a while since this issue was created, I'm not sure if it's still relevant to you or not. If there's more to ask, please feel free to reopen this topic.
